Adding support for django-nested-admin
bhch/django-jsonform pull request #67
Opened 2022-09-27 16:34 UTC by trumpet2012

Added support for django-nested-admin by moving the initialization function to a separate media script that watches for the `data-django-jsonform` data attribute and uses its json value to configure the form. This allows django-nested-admin to update the input IDs while allowing django-jsonform to still be able to find and initialize itself correctly.

(The other PR had a bad branch name)

2022-09-28 13:02 UTC, bhch requested changes
Hello, thank you for this Pull Request. Really appreciate the work you've done here.

I've left a few comments with requests for changes. Everything else looks good.

2022-09-28 13:30 UTC, trumpet2012 commented on django_jsonform/static/django_jsonform/index.js
> +  window.addEventListener("load", function() {
Good point, I've updated it to use `DOMContentLoaded`.

2022-09-28 13:52 UTC, trumpet2012 commented on django_jsonform/widgets.py
> +                'data': value or '',
Ah yeah that makes sense. I've update that as well.

2022-09-28 13:52 UTC, trumpet2012 commented on django_jsonform/widgets.py
> +            "django_jsonform/index.js",
fixed.

2022-09-28 13:54 UTC, trumpet2012 commented
@bhch thanks for the feedback and catching those issues! It should be good for you to re-review again.

2022-09-29 03:21 UTC, merged

2022-10-09 08:46 UTC, bhch commented
Hello, I've released this in [v2.13.0](https://github.com/bhch/django-jsonform/releases/tag/v2.13.0). Thank you for your contribution.